server:
  port : 1999
       
         
spring:
  application:
    name: KPL-SERVICE
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: test1
#    url: jdbc:postgresql://containers-us-west-118.railway.app:7479/railway
#    password: mzdEDSBNQOcFThIsQfVP
    url: jdbc:postgresql://dpg-cihs36iip7vpelqh3ppg-a.oregon-postgres.render.com:5432/kpl_2023_main_db_test1
    password: 7yM17BtUs6wySfvkoG0PhKjQCSkECMmF
    tomcat.max-active: 2
    hikari:
      maximum-pool-size: 2
      auto-commit: true

  jpa:
    generate-ddl: 'true'
    database-platform:  org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000 
          connctiontimeout: 5000
          writetimeout: 5000
       
    host: smtp.gmail.com    
    username: kpl2023prod@gmail.com
    password: vhijfojqbbzygyvi
    port: 587   
springfox:
  documentation:
    swagger-ui:
      base-url: /kplService 